# Generated by Django 2.2.7 on 2019-12-16 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=-1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('description', models.TextField(null=True)),
                ('members', models.ManyToManyField(related_name='queues', through='dj_queue.Membership', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_queue.Queue'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('queue', 'member')},
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('DECLINE', 'DECLINE')], default='DECLINE', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_queue.Queue')),
            ],
            options={
                'unique_together': {('queue', 'member')},
            },
        ),
    ]
