# Generated by Django 2.2.7 on 2019-11-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_queue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='users',
            new_name='user',
        ),
    ]
