# Generated by Django 2.2.7 on 2019-11-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
