# Generated by Django 2.2.7 on 2019-11-28 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dj_queue', '0002_auto_20191126_1108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('queue', 'member')},
        ),
    ]
